version: '3.4'

services:   
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=TradeScriptRunnerDb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=gamer4everlasting@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin
        
volumes: 
  database-data:
  pgadmin:
      